//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	config "github.com/gardener/gardener-extension-postgres-operator/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*PostgresConfig)(nil), (*config.PostgresConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PostgresConfig_To_config_PostgresConfig(a.(*PostgresConfig), b.(*config.PostgresConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.PostgresConfig)(nil), (*PostgresConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_PostgresConfig_To_v1alpha1_PostgresConfig(a.(*config.PostgresConfig), b.(*PostgresConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PostgresConfigSpec)(nil), (*config.PostgresConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PostgresConfigSpec_To_config_PostgresConfigSpec(a.(*PostgresConfigSpec), b.(*config.PostgresConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.PostgresConfigSpec)(nil), (*PostgresConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_PostgresConfigSpec_To_v1alpha1_PostgresConfigSpec(a.(*config.PostgresConfigSpec), b.(*PostgresConfigSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_PostgresConfig_To_config_PostgresConfig(in *PostgresConfig, out *config.PostgresConfig, s conversion.Scope) error {
	if err := Convert_v1alpha1_PostgresConfigSpec_To_config_PostgresConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PostgresConfig_To_config_PostgresConfig is an autogenerated conversion function.
func Convert_v1alpha1_PostgresConfig_To_config_PostgresConfig(in *PostgresConfig, out *config.PostgresConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_PostgresConfig_To_config_PostgresConfig(in, out, s)
}

func autoConvert_config_PostgresConfig_To_v1alpha1_PostgresConfig(in *config.PostgresConfig, out *PostgresConfig, s conversion.Scope) error {
	if err := Convert_config_PostgresConfigSpec_To_v1alpha1_PostgresConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_PostgresConfig_To_v1alpha1_PostgresConfig is an autogenerated conversion function.
func Convert_config_PostgresConfig_To_v1alpha1_PostgresConfig(in *config.PostgresConfig, out *PostgresConfig, s conversion.Scope) error {
	return autoConvert_config_PostgresConfig_To_v1alpha1_PostgresConfig(in, out, s)
}

func autoConvert_v1alpha1_PostgresConfigSpec_To_config_PostgresConfigSpec(in *PostgresConfigSpec, out *config.PostgresConfigSpec, s conversion.Scope) error {
	out.VolumeSize = in.VolumeSize
	out.Replicas = in.Replicas
	out.Users = *(*map[string][]string)(unsafe.Pointer(&in.Users))
	out.Databases = *(*map[string]string)(unsafe.Pointer(&in.Databases))
	out.PostgresVersion = in.PostgresVersion
	return nil
}

// Convert_v1alpha1_PostgresConfigSpec_To_config_PostgresConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_PostgresConfigSpec_To_config_PostgresConfigSpec(in *PostgresConfigSpec, out *config.PostgresConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PostgresConfigSpec_To_config_PostgresConfigSpec(in, out, s)
}

func autoConvert_config_PostgresConfigSpec_To_v1alpha1_PostgresConfigSpec(in *config.PostgresConfigSpec, out *PostgresConfigSpec, s conversion.Scope) error {
	out.VolumeSize = in.VolumeSize
	out.Replicas = in.Replicas
	out.Users = *(*map[string][]string)(unsafe.Pointer(&in.Users))
	out.Databases = *(*map[string]string)(unsafe.Pointer(&in.Databases))
	out.PostgresVersion = in.PostgresVersion
	return nil
}

// Convert_config_PostgresConfigSpec_To_v1alpha1_PostgresConfigSpec is an autogenerated conversion function.
func Convert_config_PostgresConfigSpec_To_v1alpha1_PostgresConfigSpec(in *config.PostgresConfigSpec, out *PostgresConfigSpec, s conversion.Scope) error {
	return autoConvert_config_PostgresConfigSpec_To_v1alpha1_PostgresConfigSpec(in, out, s)
}
